# Generated by Django 3.2.9 on 2022-10-20 12:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RightsSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('administration_module', 'Administration Module'), ('projects_module', 'Projects Module'), ('hr_module', 'HR Module'), ('reports_module', 'Reports Module'), ('inventory_module', 'Inventory Module'), ('filemanager_module', 'File Manager Module'), ('suggestionbox_module', 'Suggestion Box Module'), ('manage_archiving', 'Manage Archiving')),
                'managed': False,
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('box_number', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='clients/logos')),
                ('currency_symbol', models.CharField(blank=True, max_length=255, null=True)),
                ('currency_location', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], default=('right', 'Right'), max_length=10)),
                ('login_active', models.BooleanField(db_index=True, default=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_client', models.BooleanField(default=True, editable=False)),
                ('is_active', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('name', models.CharField(blank=True, db_index=True, max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.TextField(blank=True, null=True)),
                ('action_flag', models.PositiveSmallIntegerField(choices=[[1, 'Addition'], [2, 'Change'], [3, 'Deletion'], [4, 'Other Action']], default=4)),
                ('change_message', models.TextField(blank=True, null=True)),
                ('action_time', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'verbose_name': 'log',
                'verbose_name_plural': 'logs',
                'ordering': ('-action_time',),
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('code', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('message', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, choices=[('banks', 'Bank'), ('departments', 'Department'), ('jobs', 'Jobs'), ('allowances', 'Allowance'), ('leave-categories', 'Leave Categories'), ('holidays', 'Holidays'), ('deductions', 'Deductions'), ('taxes', 'Tax'), ('sections', 'Sections')], db_index=True, max_length=255)),
                ('is_formula', models.BooleanField(blank=True, default=False)),
                ('formula', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='TermMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('meta_key', models.CharField(blank=True, max_length=255)),
                ('meta_value', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, editable=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
