# Generated by Django 3.2.9 on 2022-10-20 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rightssupport',
            options={'default_permissions': (), 'managed': False, 'permissions': (('administration_module', 'Administration Module'), ('projects_module', 'Projects Module'), ('hr_module', 'HR Module'), ('reports_module', 'Reports Module'), ('manage_archiving', 'Manage Archiving'))},
        ),
        migrations.RemoveField(
            model_name='client',
            name='is_client',
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='client',
            name='login_active',
        ),
        migrations.RemoveField(
            model_name='client',
            name='password',
        ),
    ]
