# Generated by Django 3.2.9 on 2022-10-20 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartOfAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('code', models.CharField(blank=True, max_length=255)),
                ('account_type', models.CharField(blank=True, choices=[('1', 'Assets'), ('2', 'Liabilities'), ('3', 'Income'), ('4', 'Expenses'), ('5', 'Capital')], max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, choices=[(1, 'Active'), (2, 'Inactive')], default=1)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_chartofaccount_created_by', related_query_name='finances_chartofaccounts', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.chartofaccount')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='finances_chartofaccount_updated_by', related_query_name='finances_chartofaccounts', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last updated on')),
                ('transaction_code', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(blank=True)),
                ('transaction_type', models.CharField(blank=True, max_length=255)),
                ('transaction_mode', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=45)),
                ('cheque_number', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.FloatField(blank=True, default=0)),
                ('payee', models.CharField(blank=True, max_length=255, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_transaction_created_by', related_query_name='finances_transactions', to=settings.AUTH_USER_MODEL)),
                ('gl_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.chartofaccount')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='finances_transaction_updated_by', related_query_name='finances_transactions', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
