# Generated by Django 3.2.9 on 2022-10-20 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_transaction_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('assets', 'Assets'), ('liabilities', 'Liabilities'), ('income', 'Income'), ('expenses', 'Expenses'), ('capital', 'Capital')], max_length=255),
        ),
    ]
