# Generated by Django 3.2.9 on 2022-12-06 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_currentuser.db.models.fields
import django_currentuser.middleware


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221206_1411'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finances', '0003_alter_chartofaccount_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated on')),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('sender_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_type', models.CharField(choices=[('invoice', 'Invoice'), ('credit_note', 'Credit note'), ('qoute', 'Quote')], default='invoice', max_length=20)),
                ('due_days', models.IntegerField(default=14)),
                ('is_credited', models.BooleanField(default=False)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('bank_account', models.CharField(blank=True, max_length=266, null=True)),
                ('gross_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('description', models.TextField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.client')),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_invoice_created_by', related_query_name='finances_invoices', to=settings.AUTH_USER_MODEL)),
                ('is_credit_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finances.invoice')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='finances_invoice_updated_by', related_query_name='finances_invoices', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('asset', 'Assets'), ('liability', 'Liabilities'), ('income', 'Income'), ('expense', 'Expenses'), ('capital', 'Capital')], max_length=255),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated on'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='last updated on'),
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='last updated on')),
                ('title', models.CharField(max_length=255)),
                ('quantity', models.FloatField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('vat_rate', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finances_item_created_by', related_query_name='finances_items', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finances.invoice')),
                ('updated_by', django_currentuser.db.models.fields.CurrentUserField(default=django_currentuser.middleware.get_current_authenticated_user, null=True, on_delete=django.db.models.deletion.CASCADE, on_update=True, related_name='finances_item_updated_by', related_query_name='finances_items', to=settings.AUTH_USER_MODEL, verbose_name='last updated by')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
