# Generated by Django 3.2.9 on 2022-12-06 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_invoice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='title',
        ),
    ]
