# Generated by Django 3.2.9 on 2022-12-06 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0009_invoice_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='discount_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='gross_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='net_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='vat_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='net_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='unit_price',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
