# Generated by Django 3.2.9 on 2023-08-16 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_auto_20221206_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='appear_on_trial_balance',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_closing_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='is_opening_stock',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
