# Generated by Django 3.2.9 on 2023-09-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_auto_20230816_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Fixed assets', 'Fixed assets'), ('Current assets', 'Current assets'), ('Current liabilities', 'Current liabilities'), ('Long term liabilities', 'Long term liabilities'), ('Revenue', 'Revenue'), ('Operating expenses', 'Operating expenses'), ('Capital expenses', 'Capital expenses'), ('Owners equity', 'Owners equity'), ('Retained earnings', 'Retained earnings'), ('Bank', 'Bank'), ('Dividends', 'Dividends'), ('Accounts payable', 'Accounts payable'), ('Accounts receivable', 'Accounts receivable'), ('Cost of goods sold', 'Cost of goods sold'), ('Purchases', 'Purchases')], max_length=255),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='finances.chartofaccount'),
        ),
    ]
